### ISSUE TITLE
the getter 'accentcolor' isn't defined for the class 'themedata'.

### ISSUE THREAD

**Issue by hirensamtani** [JoseBarreto1/chips_choice_null_safety#8]
the getter 'accentcolor' isn't defined for the class 'themedata'.
This happened as Theme.of(context).accentColor is now deprecated

**Comment by hirensamtani** [comment]
Changes done on forked branch. Awaiting merge.

**Comment by jbarretojr** [comment]
merge done. Soon I will update the plugin.

**Comment by hungrybearpls** [comment]
Still getting the error after replacing all instances of Theme.of(context).accentColor with Theme.of(context).colorScheme.secondary. Using   chips_choice_null_safety: ^2.0.6
